# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Magnolia Christian Academy of the Ozarks
email: info@magnoliachristianacademy.org
description: >
  Parent taught and lead homeschool cooperative in the Springfield, Missouri area.
baseurl: ""
url: "http://www.magnoliachristianacademy.org"
twitter_username:
github_username:  mcaoto

# Build settings
markdown: kramdown
